title: Global Lawfirm
description: "Full Service Legal Solutions terpadu bagi individu, korporasi, PMA, lembaga, hingga instansi pemerintah."
url: ""
baseurl: ""

# Pengaturan agar Markdown diproses dengan rapi
markdown: kramdown

# Pengaturan Plugin SEO
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Pengaturan SEO Tag
title: Global Lawfirm
description: "Firma hukum terkemuka di Sidoarjo yang memberikan layanan litigasi, korporasi, kepailitan, perizinan, hingga pendampingan hukum komprehensif."
logo: "/images/hero-bg.png"
